

server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kute/spring-cloud-config
          search-paths: config
#          force-pull make Spring Cloud Config Server force pull from remote repository if the local copy is dirty.
          force-pull: true
#          username: kute
#          password:
        default-label: master
        default-application-name: spring-cloud-config-server
        default-profile: prod
#     branch for pull operation
      label: master
      profile: prod
      enabled: true


