

server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kute/spring-cloud-config
          search-paths: config
#          username: kute
#          password:
        default-label: master
        default-application-name: application
#     branch for pull operation
      label: master


